; PlatformIO Project Configuration File
; Pole Trans Monitor - Pole Transformer Monitoring
; https://docs.platformio.org/en/latest/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
  -I include
  -I src
  -DTINY_GSM_MODEM_A7672X
lib_deps =
  https://github.com/mandulaj/PZEM-004T-v30#v1.2.1
  adafruit/Adafruit MAX31865 library
  vshymanskyy/TinyGSM
  bblanchon/ArduinoJson
  https://github.com/tzapu/WiFiManager.git
