# Generated by Django 4.2.29 on 2026-03-06 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nominal_voltage', models.FloatField(default=220)),
                ('nominal_freq', models.FloatField(default=60)),
                ('rated_kva', models.FloatField(default=15)),
                ('rated_current', models.FloatField(default=68)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('current', models.FloatField(blank=True, null=True)),
                ('apparent_power', models.FloatField(blank=True, null=True)),
                ('power_factor', models.FloatField(blank=True, null=True)),
                ('frequency', models.FloatField(blank=True, null=True)),
                ('oil_temp', models.FloatField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('normal', 'Normal'), ('heavy_peak_load', 'Heavy Peak Load'), ('danger_zone', 'Danger Zone'), ('overload', 'Overload'), ('severe_overload', 'Severe Overload'), ('heavy_load', 'Heavy Load'), ('abnormal', 'Abnormal'), ('poor_power_quality', 'Poor Power Quality'), ('critical', 'Critical')], default='normal', max_length=30)),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitor.transformer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(choices=[('normal', 'Normal'), ('heavy_peak_load', 'Heavy Peak Load'), ('danger_zone', 'Danger Zone'), ('overload', 'Overload'), ('severe_overload', 'Severe Overload'), ('heavy_load', 'Heavy Load'), ('abnormal', 'Abnormal'), ('poor_power_quality', 'Poor Power Quality'), ('critical', 'Critical')], max_length=30)),
                ('message', models.TextField()),
                ('sms_sent', models.BooleanField(default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitor.transformer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
