# Generated by Django 4.2.29 on 2026-04-09 16:13#

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_transformer_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformer',
            name='pending_energy_reset',
            field=models.BooleanField(default=False),
        ),
    ]
