# Generated by Django 4.2.30 on 2026-04-25 06:02

from django.db import migrations, models
import monitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_transformer_reading_interval_minutes_readingbuffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, unique=True)),
                ('bin_file', models.FileField(upload_to=monitor.models._firmware_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='transformer',
            name='pending_open_portal',
            field=models.BooleanField(default=False),
        ),
    ]
