# Generated by Django 4.2.30 on 2026-05-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_reading_readingbuffer_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='apparent_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='energy_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='frequency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='oil_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='power_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='real_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['transformer', '-timestamp'], name='alert_xfmr_ts_desc_idx'),
        ),
    ]
